### ISSUE TITLE
Repository deleted from Pc 

### ISSUE THREAD

**Issue by NLStevenson** [shiftkey/desktop#1046]
### The problem

Repository for a game I'm working on was deleted between uses of github desktop. Files not in folder, trash, anywhere that I can see. including log for last commit and then log on day issue found. Receiving error "Can't Find Mythora_Dev" as the repository is no longer in the folder. Folder is "/home/nate/Documents/GitHub/Mythora_Dev"

I can reload repository from github, but I believe this is unexpected/unwelcome behavior for desktop.

### Release version

3.3.12-linux2

### Operating system

Linux: Ubuntu

### Log files

[2024-04-01.desktop..log](https://github.com/shiftkey/desktop/files/14937541/2024-04-01.desktop.log)
[2024-03-28.desktop..log](https://github.com/shiftkey/desktop/files/14937542/2024-03-28.desktop.log)

**Comment by shiftkey** [comment]
> I can reload repository from github, but I believe this is unexpected/unwelcome behavior for desktop.

Do you have any more recent logs from the app than April 1? I don't see anything resembling that error to help me understand why the repository might have been removed from disk...

**Comment by NLStevenson** [comment]
This is the log after the repository was gone.
[2024-04-09.desktop..log](https://github.com/shiftkey/desktop/files/14937667/2024-04-09.desktop.log)

**Comment by shiftkey** [comment]
That log file still doesn't show anything interesting or relevant.

The relevant code path that I can think of is when the app tries to refresh the local repository state and it can't find the repository folder on disk - what we do then is set a flag in the app and then avoid refreshing the repository:

https://github.com/shiftkey/desktop/blob/1b7a555c2f70f53d91e5c2b99f4d6d49a56cca13/app/src/lib/stores/app-store.ts#L3364-L3389

We then show this view to the user - because there's no Git data to see - to try and help them recover:

https://github.com/shiftkey/desktop/blob/7e58e475452bcf7e9db4f984f7e8e7b33a8a4bca/app/src/ui/missing-repository.tsx#L137-L148

Could something have happened on disk from some other program to rename the directory? Or perhaps a parent directory being renamed?

Unless I can find an error message that suggests it's been removed I'm going to lean on the historical behaviour where once it can't find a repository on disk we "quarantine" it and display this message, which it sounds like what you saw here...

**Comment by NLStevenson** [comment]
The repository is missing. I think what you're saying is that when the repository is missing this is the message displayed. It sounds like there is not any information as to why the repository is missing in the logs, and you can't think of any reason why Git would remove the repository/move the repository if I haven't interacted with it.

in that case, there's nothing to do but call a surrender since I have no way to track down when the missing file was moved/modified and by what program it was moved/modified. Thank you for your time.
