### ISSUE TITLE
GitHub Desktop does not respect KDE Plasma "Keyboard accelerators visibility" setting

### ISSUE THREAD

**Issue by Tiagoquix** [shiftkey/desktop#1059]
### The problem

Hi there.

The app does not respect KDE Plasma's "Keyboard accelerators visibility" setting (letter underlines).

![image](https://github.com/shiftkey/desktop/assets/30274161/6fac6af1-da89-4c59-925e-3811190a4cd9)

![image](https://github.com/shiftkey/desktop/assets/30274161/b51c6ee8-18fe-4601-80fb-7b6b58867e3c)

Is there a fix available for this? Thanks in advance.

### Release version

3.3.12-linux2 (x64)

### Operating system

Fedora Linux 40 KDE

**Comment by shiftkey** [comment]
The app itself is built using Electron, so it's support of window manager settings is currently limited. It's been a while since I've looked into the Chromium internals to see how it detects things like light/dark mode and it may not be possible to easily check this for different window managers. 

As this would likely require contributions to Chromium or Electron to detect this setting I'm going to tag this as an upstream issue but I don't have plans to support this.

**Comment by Tiagoquix** [comment]
The issue has been fixed at some point with some update.
