### ISSUE TITLE
default browser not used when launching external links

### ISSUE THREAD

**Issue by tdesmet** [shiftkey/desktop#148]
## Description
When you want to use any function that should open the browser like `Compare on Github` or `Create Pull Request`, github desktop tries to open firefox instead of the default browser (chrome in my case)

## Version
* GitHub Desktop: 1.6.6-linux2
* Operating system: Ubuntu 19.04

## Steps to Reproduce

1. make sure your default browser is not firefox
2. Click on `Compare on Github` in the Branch menu
3. Firefox is opened instead of the default browser

### Expected Behavior

The default browser should open

### Actual Behavior

Firefox opens and crashes

**Comment by shiftkey** [comment]
@tdesmet thanks for the feedback.

We're using the Electron [shell.openExternal](https://github.com/electron/electron/blob/v3.1.6/docs/api/shell.md#shellopenexternalurl-options-callback) function in Desktop and providing just the desired URL so I'm not sure what other config we need to provide within the app.

Looking at what Electron is doing under the hood, it should be deferring to `xdg-open`:

https://github.com/electron/electron/blob/73158a6419a3e2da9e4d523e1131052abd28fbbb/atom/common/platform_util_linux.cc#L84-L91

```c++
bool OpenExternal(const GURL& url, bool activate) {
  // Don't wait for exit, since we don't want to wait for the browser/email
  // client window to close before returning
  if (url.SchemeIs("mailto"))
    return XDGEmail(url.spec(), false);
  else
    return XDGOpen(url.spec(), false);
}
```

https://github.com/electron/electron/blob/73158a6419a3e2da9e4d523e1131052abd28fbbb/atom/common/platform_util_linux.cc#L57-L59

```c++
bool XDGOpen(const std::string& path, const bool wait_for_exit) {
  return XDGUtil("xdg-open", path, wait_for_exit);
}
```

It's been a while since I looked at `xdg` and how to manage configuration, but that's what Electron is looking for on your machine to figure out what to launch.

**Comment by tdesmet** [comment]
This is strange, running `xdg-open http://google.com` in a shell opens chrome.

**Comment by davidmcl** [comment]
Same for me on Linux Mint 19.1 (Ubuntu 18.04, Bionic)

xdg-open default is definitely Chrome for my user profile. 

Thanks,
David

**Comment by tdesmet** [comment]
I have been trying to debug this a bit more, if firefox is not open then firefox tries to launch but crashes. If firefox is open then a new tab is opened with the url.

I have an app that runs on electron 5 that does not show this behaviour, callen shell.openItem or shell.openExternal opens the default browser (chrome in my case) and no crashes occur.

**Comment by tdesmet** [comment]
Another update, I tried the AppImage instead of the snap and with the AppImage the default browser is launched. So this seems to be a problem with the snap.

**Comment by Jord-JD** [comment]
I'm also experiencing the issue of my default browser not being used when using the snap package.

**Comment by davidmcl** [comment]
Yes...as a follow-up, I too used the snap package.

**Comment by shiftkey** [comment]
Thanks for clarifying this is related to the Snap package. For now I've stopped shipping snaps because of more serious issues with the app (see #202 for tracking that work) but I'll leave this open as a reminder to revisit this after that's been resolved.

**Comment by shiftkey** [comment]
I'm going to leave a couple of key Snap issues open and close out the rest for now (they're tagged, and should be cross-referencing #202) to keep the issue tracker focused on current priorities.
