### ISSUE TITLE
Repositories in Organization(s) that the user is part of don't show up when cloning repos

### ISSUE THREAD

**Issue by AluminiumTech** [shiftkey/desktop#15]
Summary: Users are unable to clone repositories from the organization(s) the user is part of in the cloning repositories menu.

![](https://user-images.githubusercontent.com/14107316/34097052-9f4ae19a-e412-11e7-987e-c7ed611b61ad.png)

GitHub Desktop Version: 1.0.11 RC1 for Linux

OS Version: Ubuntu 17.10 with latest updates.

### Steps to Reproduce

1. Open GitHub Desktop App
2. Click on "File" and "Clone Repository.
3. Look through repository list under GitHub.com

**Expected behavior:** Show repositories from organizations that the user is part of.

**Actual behavior:** Shows only repositories that belong to the user.

**Reproduces how often:** Every time.

**Comment by shiftkey** [comment]
I'm fairly sure this is because organizations can restrict [third-party access to apps](https://help.github.com/articles/about-oauth-app-access-restrictions/) - we talked about this in https://github.com/desktop/desktop/issues/3364 when the app runs in development mode - and the Linux app is currently doing the same.

I'll close this out and use #13 to track when we use the correct OAuth details in the next build.
