### ISSUE TITLE
SIGSEGV Address boundary Error with Appimage

### ISSUE THREAD

**Issue by mrchainman** [shiftkey/desktop#220]
### Describe the bug

I downloaded the Appimage and get the following error, when I try to execute it:
`fish: './Github' terminated by signal SIGSEGV (Address boundary error)`
Same error is reported with other shells.

### Version & OS
Newest version from appimagehub.com
Running void Linux with Kernel: 5.4.22_1

### Steps to reproduce the behavior

1. Donwload the Image from appimagehub.com on void linux.
2. Make it executable.
3. Get the error mentioned above

### Expected behavior

The App opens

### Actual behavior

The App does not open and the mentioned error is reported.

**Comment by shiftkey** [comment]
> Newest version from appimagehub.com

I'm not publishing these, and looking at https://www.pling.com/p/1265114 the latest is `1.4.0` from October 2018.

Please use the latest version from [our releases page](https://github.com/shiftkey/desktop/releases) (current `2.3.1`, released last month) and confirm whether the issue is still reproducible.

**Comment by mrchainman** [comment]
Issue is not reproducible, thanks for the quick response, I am closing the issue.
