### ISSUE TITLE
Unable to clone organization repo

### ISSUE THREAD

**Issue by jfgordon2** [shiftkey/desktop#229]
### Describe the bug

Pasting a url for a private repo under an organization my github user is associated with, I get a 404 error connecting through the linux GitHub Desktop client.  This works using the same credentials through git on the command line, and on the windows version of the client.

### Version & OS

GitHub Desktop Version 2.3.1-linux1
elementary OS 5.1.2 Hera

### Steps to reproduce the behavior

1. File > Clone Repository
2. Paste HTTPS://URL.git of organization repo
3. Enter Authorized User Credentials

### Expected behavior

Clone repo to local, and display in client

### Actual behavior

Client reports that the repo is not found

### Logs

> 2020-03-17T03:14:31.609Z - warn: [ui] fetchRepository: '{organization\repo name}' returned a 404
> 2020-03-17T03:14:31.610Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: {repo name} - jfgordon2 (has token)
> 2020-03-17T03:14:32.731Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.084s)
> 2020-03-17T03:14:32.732Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository '{repo url}' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
> 2020-03-17T03:14:32.975Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable

### Additional context

My local repos are pulling just fine, and I am not an admin in the organization.

**Comment by shiftkey** [comment]
I still think this is the same as #126 and thus #72 because the app generates it's own OAuth token (with the scopes it needs) for cloning with Git. This is separate to whatever is set in your credential helper, and would likely be caught by [OAuth App access restrictions](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-oauth-app-access-restrictions).

**Comment by Yanujz** [comment]
@shiftkey What you suggest to do then? On windows and Mac is working properly.
i've the same problem.

Thank's for your help!

**Comment by jfgordon2** [comment]
@Yanujz while I would love to do this directly in the GitHub Desktop client like my other repos, I'm just using the git CLI commands.  You can cache credentials like this: https://help.github.com/en/github/using-git/caching-your-github-password-in-git

**Comment by Yanujz** [comment]
Thank you @jfgordon2! If you find any other solution just keep in touch, i'll do the same :D

**Comment by shiftkey** [comment]
> What you suggest to do then? On windows and Mac is working properly.

This is because I maintain the unofficial releases for Linux, and it doesn't contain the OAuth details required to behave the same. This is being discussed in https://github.com/desktop/desktop/issues/1525 (please upvote if you care) but #72 is tracking this known limitation.

As I want to keep this separate until the team is interested in official support, the only other option here would be for me to embed a new set of OAuth details that would belong to a distinct entity to avoid confusion with the main "GitHub Desktop" product. That's branding work I'm not able to take on currently, and I want to focus currently on ensuring the app installs and works on various distros.

Introducing a new brand also won't address the solution completely because organization administrators need to [approve access](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) to this new application.

The command line works here because you're creating a token directly associated with your account, rather than delegating to an OAuth application.

**Comment by shiftkey** [comment]
Closing this out because #72 is the underlying issue here.
