### ISSUE TITLE
github command remains as foreground process until killed

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#238]
As part of reviewing #231 I noticed that running `github` from a terminal (without parameters) would launch the app and wait for it to complete. My thinking here is that a GUI app should result in a background process, rather than block the terminal until it's closed, but maybe I'm missing something.

The same behaviour also occurs when you have parameters, e.g. `github open [path]`.

These scenarios worked as expected:

 - `github &`  -> program runs as a background process, window launches
 - `github [arguments]` when application is already open -> window receives focus, prompt appears

cc @jfgordon2 for thoughts

**Comment by jfgordon2** [comment]
Ah gotcha - this is because the process is started within the shell.  It's the same as launching any other program that way (try `google-chrome` for instance).

If you want to push it to a background process within the shell, you can append an `&` to the command

For instance:  `github open [path] &`

I'm not quite sure where to start, but is this behavior something we'd prefer to modify for just the `github` execution?

**update**
I’ve posted a patch that will immediately detach the execution from the controlling terminal.  It operates on the github command but not github-desktop (probably not as important anyway especially since running github by itself will also launch the app)

**Comment by shiftkey** [comment]
@jfgordon2 thanks for the quick reply and PR

> I'm not quite sure where to start, but is this behavior something we'd prefer to modify for just the `github` execution?

Yeah, this makes sense as `github-desktop` is the binary represents the main program (essentially renamed from `electron`) and I'd prefer to leave that as-is.

I wrote this up because macOS seems to work in this way, and I like this behaviour for two main reasons:

 - consistency across platforms wherever possible
 - switching between the terminal and the app is going to become tedious quickly if I need to remember to close and re-run the command with an `&` on it
