### ISSUE TITLE
In clone repository window there are no team repositories only mine (under "Your's repositories")

### ISSUE THREAD

**Issue by skakunm** [shiftkey/desktop#242]
### Describe the bug

On Windows GItHub Desktop app when I click clone repository, in the Windows app version I can see one list named "Your's repositories" and bellow it there is a team repository name and bellow it team repositories are listed. On the other hand on the Ubuntu 16.04 Github Desktop app there are only my repositories and no team repositories. Even when I manually copy the url to the URL section it can't authenticate. After that I manually cloned the repository in terminal using the same username and password and it worked.

### Version & OS

I have GitHub Desktop Version 2.4.0-linux1
and Ubuntu 16.04

### Steps to reproduce the behavior

1. Install the app
2. Open the app
3. Click "Clone a repository from the Internet..."
4. Scroll down -> there is no repository
5. Copy repository from the web
6. Click URL tab in the Clone a repository window
7. Paste the URL and click Clone
8. Type adequate username and password

**Comment by shiftkey** [comment]
@skakunm thanks for the report. I believe this is because of [OAuth App Access restrictions](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-oauth-app-access-restrictions) being enabled for these organizations, which is blocking the app for Linux.

In #72 I indicate that I'm not using the same OAuth app details as the Windows and macOS applications, because I believe that's part of official support for GitHub Desktop and should not be added before that's on their roadmap. 

I added a comment https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 with some more recent thoughts about alternative approaches, none of which are particularly satisfying to me.

Please follow along with #72 in the meantime.
