### ISSUE TITLE
[Regression] GitHub desktop no longer prompts for authentication for GitLab repositories

### ISSUE THREAD

**Issue by ipkpjersi** [shiftkey/desktop#295]
### Describe the bug

When attempting to clone a private GitLab repository, GitHub desktop no longer prompts for a username and password, like this:
![](https://i.imgur.com/T8gv2wE.png)

Instead, it displays an error: 
![](https://i.imgur.com/JahsB3M.png)

I am using HTTPS, not SSH, to clone the repository. This used to work just fine in GitHub desktop and no longer works.

### Version & OS

Version: Version 2.5.0-linux1
OS: Ubuntu 18.04 with Xfce 4.12

### Steps to reproduce the behavior

1. Click File
2. Click Clone repository
3. Click the URL tab
4. Enter the HTTPS GitLab URL of your repository

### Expected behavior

I expect it to prompt for my GitLab username and password - accepting a token if the GitLab account has 2FA enabled, of course.

### Actual behavior

It displays an error and does not prompt for authentication.

### Logs

```
(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-06-12T16:43:55.031Z - info: [ui] Background fetch for 5 repositories took 6.221sec
2020-06-12T16:44:08.161Z - info: [main] Received possible protocol arguments: 1
2020-06-12T16:44:18.529Z - info: [ui] [AppStore] adding repository at /home/user/Desktop/dev/repo to store
2020-06-12T16:44:22.349Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/ipkpjersi/repo.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

### Additional context

I really hope this is a regression and not a concious design decision to make GitLab no longer supported. I think it's just a bug and I am hoping it will eventually get solved. I am not sure if I need to report this here or upstream on the main GitHub Desktop repository so I reported it here for now.

**Comment by shiftkey** [comment]
@ipkpjersi this bit looks like the root of the problem:

```
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/ipkpjersi/repo.git/'
```

Do you have 2FA enabled on your account? Or something else that might be causing the GitLab server to reject your credentials?

**Comment by ipkpjersi** [comment]
That's the thing, it didn't even prompt me *for* my credentials when I tried cloning the repo for the first time.

I was able to clone the repo normally through git CLI, then add the repo locally through GitHub Desktop, then when I tried fetching origin, it *then* prompted me for my credentials and it worked normally with of course caching my credentials and being able to clone other repos on my GitLab account.

It's like it doesn't know when to prompt for credentials the first time cloning a GitLab repo.

**Comment by shiftkey** [comment]
@ipkpjersi 

> I was able to clone the repo normally through git CLI

Cloning the repository from outside GitHub Desktop is using a different credential manager to the behaviour in GitHub Desktop, so that might explain the difference here.

> then when I tried fetching origin, it then prompted me for my credentials and it worked normally with of course caching my credentials and being able to clone other repos on my GitLab account.

This is the bit that's confusing to me. It doesn't look like that fetch worked based on the log, so it may be continuing to retry in a loop because it doesn't have valid credentials.

**Comment by ipkpjersi** [comment]
I will give a complete listing of what happened, hopefully that will help.

I created a new GitLab account and a repository, and then I opened up GitHub Desktop and attempted to clone a private repository using it via HTTPS (not SSH). Instead of prompting me for credentials like it should have, it kept saying authentication failed. After it was clear this would not work, I then cloned it via `git clone` via HTTPS which worked successfully. I added the local repository in GitHub Desktop (Add local repository), clicked on fetch origin, and it then prompted me for my GitLab username and password. I entered them and was able to successfully fetch origin. After that, I was able to clone all repositories on my GitLab account using GitHub Desktop.

I attempted this on GitHub Desktop on Windows and it appears to have worked, so I believe that it does appear to be a problem limited to the fork.

**Comment by shiftkey** [comment]
> I created a new GitLab account and a repository, and then I opened up GitHub Desktop and attempted to clone a private repository using it via HTTPS (not SSH). Instead of prompting me for credentials like it should have, it kept saying authentication failed. 

I tried these steps with my GitLab account that hasn't been used in GitHub Desktop and it prompted me for authentication to clone a private repository, and my password was accepted because it doesn't have 2FA enabled. So let's dig into what could be different between your setup and mine.

I'd like to see the logs from when this happened, to understand what error it was giving you and whether it was different to the fetch error. There could be a couple of things involved:

 - were there previous credentials that the app found locally and used, but it failed to work with the clone?
 - was it failing for the same reason during the clone as the fetch? the error handling may be different in each place

The log should contain more information about why it failed on that first clone, and I'd like to confirm there are successful Git operations occurring in the app.

> I attempted this on GitHub Desktop on Windows and it appears to have worked, so I believe that it does appear to be a problem limited to the fork.

Authentication is a tricky area with Git, and while there's likely some minor differences between the platforms there's not much specific that I can think of which I've done in this fork that isn't available upstream.

**Comment by shiftkey** [comment]
> I am using HTTPS, not SSH, to clone the repository. This used to work just fine in GitHub desktop and no longer works.
>
> ...
>
> Version: Version 2.5.0-linux1

I should have noticed earlier that this wasn't the latest version, and I checked some of the upstream changes in the release notes. I see this PR was added in `2.5.1` and it might be the fix you need: https://github.com/desktop/desktop/pull/9777

> I attempted this on GitHub Desktop on Windows and it appears to have worked

Which version did you use on Windows? If it is later than `2.5.0` then we might have found the root cause, and upgrading to `2.5.2` should resolve this.

**Comment by ipkpjersi** [comment]
Yep, the Windows version is 2.5.2, that's probably exactly what it was. I hadn't realized I wasn't on the latest version of GitHub Desktop on Linux (man I miss the snaps on the snap store lol)

I'm going to go ahead and close this for now since it was likely an issue upstream and was fixed upstream.
