### ISSUE TITLE
unable to push commit and pull requests

### ISSUE THREAD

**Issue by Alessio1100** [shiftkey/desktop#296]
### Describe the bug

when i push a commit or a pull request i get an error, i tried to fix all common reasons but i still can't push.
text of error :
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Version & OS
Version 2.5.2-linux1

**Comment by shiftkey** [comment]
@Alessio1100 please have a read of #281 as that may provide some context

**Comment by Sudospective** [comment]
I had this issue as well. What I found was that the project required I had an SSH key, and when I tried to clone the project again, it knew I had one, but failed to clone the project regardless. I have a password set on my key, and noticed that the client didn't ask me to input one, so that was kind of expected. However, after cloning using `git clone` from the terminal, I was able to clone over SSH from the GUI client, since the SSH key was cached to my device.

Maybe there's some issue with cloning SSH repositories in that the GUI client never asks for a password if there should be one?

**Comment by Winning117** [comment]
Per [GitHub's documentation](https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url) it says to use `git@github.com:USERNAME/REPOSITORY.git` for SSH keys instead of `https://github.com/USERNAME/REPOSITORY.git`. I just updated mine by going to Repository -> Repository settings and changing it. Once I did that I opened up a terminal and typed `git remote show origin` and that got it back on track so I could push/pull in the app again... Hopefully that works for you too :)

**Comment by Sudospective** [comment]
Right, I kinda forgot that SSH repos need that bit...Thanks, I'm sure that would help if I use SSH keys again ^-^

**Comment by Slluxx** [comment]
> Per [GitHub's documentation](https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url) it says to use `git@github.com:USERNAME/REPOSITORY.git` for SSH keys instead of `https://github.com/USERNAME/REPOSITORY.git`. I just updated mine by going to Repository -> Repository settings and changing it. Once I did that I opened up a terminal and typed `git remote show origin` and that got it back on track so I could push/pull in the app again... Hopefully that works for you too :)

thank you sir!

**Comment by shiftkey** [comment]
> Maybe there's some issue with cloning SSH repositories in that the GUI client never asks for a password if there should be one?

This is not a Linux-specific issue, and there's an upstream issue that is tracking numerous friction points about working with SSH remotes https://github.com/desktop/desktop/issues/2579 - Please follow along with that discussion.
