### ISSUE TITLE
Recent performance regressions

### ISSUE THREAD

**Issue by serkonda7** [shiftkey/desktop#342]
### Describe the bug
In the recent version the app got a lot slower and feels unresponsive.
Especially creating commits and discarding changes takes significantly more time than before.

### Version & OS
Manjaro
2.5.4-linux1

### Logs
An old log compared to a new one.
[2020-08-28.desktop.production.log](https://github.com/shiftkey/desktop/files/5225825/2020-08-28.desktop.production.log)
[2020-09-15.desktop.production.log](https://github.com/shiftkey/desktop/files/5225841/2020-09-15.desktop.production.log)

**Comment by shiftkey** [comment]
@serkonda7 thanks for the heads up.

#329 has some clues about why creating commits is slower in the latest release, and #332 is covering discarding changes and is likely the same root cause. Sadly it feels like it's a Node issue with child processes which has been challenging to isolate and confirm.

Please follow along with those issues in the meantime.
