### ISSUE TITLE
not able to sign in

### ISSUE THREAD

**Issue by padawan66** [shiftkey/desktop#348]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
@padawan66 please fill out the template with as much information as possible

**Comment by guidezpl** [comment]
### Describe the bug
Auth flow is broken
 
### Version & OS
Version 2.5.4-linux1, Debian
 
### Steps to reproduce the behavior
1. During onboarding, click sign in. A webpage opens (Chrome for me)
2. Get the following modal, click 'Open..' 
<img width="670" alt="Screen Shot 2020-09-30 at 6 31 04 PM" src="https://user-images.githubusercontent.com/6655696/94713487-2306a280-034b-11eb-89cf-1520755dd3f0.png">

### Expected behavior
Able to complete sign-in
 
### Actual behavior
Web page closes and login in the app stays pending

### Additional context
Copying the link to use on a different OS is of no help, on macOS it attempts to open the existing Github Desktop app

**Comment by padawan66** [comment]
Hi ,
Sorry for not describing the bug in detail before.
OS : PopOS 20.4 LTS
Steps to reproduce : 
1. Go to Github desktop
2. Forgot password
3. Open in browser
4. Change password in browser
5.Loader is  spinning in the sign in button ( blue button ) in the desktop github app. 

Solution : I restarted the machine. It allowed me to sign in again. Started working properly.

**Comment by padawan66** [comment]
Thanks for getting back!

**Comment by shiftkey** [comment]
Thanks for the extra context. Unfortunately I'm limited in what we can support here as Electron apps on Linux rely on `xdg-open` to locate the app when the browser completes the sign in flow - if that's not working, we're stuck.

@guidezpl can you confirm the same workaround restores behaviour for you?

**Comment by guidezpl** [comment]
This workaround didn't work for me but I found another one, see #318
