### ISSUE TITLE
prototype publishing to Open Build Service

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/desktop#363]
This has been suggested as an alternative to PackageCloud and my current set of requirements for any alternative are:

 - hosted infrastructure
 - accepts .deb directly
 - handles GPG signing natively
 - also supports RPM hosting

Any pointers or resource for getting started (I'm registered over there as `shiftkey` with a [`github-desktop`](https://build.opensuse.org/project/show/home:shiftkey:github-desktop) subproject setup) and how to automate publishing of releases (ideally from a GitHub release, but I can adapt based on what API support exists) would be greatly appreciated.

Goals:

 - [ ] can publish DEB and RPM binaries to project using API
 - [ ] can document process for adding feed based on package manager

**Comment by sarim** [comment]
I'm the author of [ibus-avro](https://github.com/sarim/ibus-avro), I used OBS in past (~9 yrs ago). **My information may be horrible outdated**, but I'll try to give some info here. 

### Backstory, feel free to ignore

After a few years I ended up discarding OBS, or OBS automatically discarded me, mainly because after each release of ubuntu (and debian and other OS's included in my project), I had to log in and check mark new distro version, make sure build is working properly etc... Over the years I didn't have the time and forgot to do that. Eventually my project didn't support the new distro versions and old versions got depreciated and deleted and eventually the project was deleted too. Back to present  some awesome volunteers took charge of packaging and now its in official debian and ubuntu repository, so no 3rd party service is required anymore. 

OBS info
==


> * hosted infrastructure

Yes, obs hosts and also they have mirrors all over the world to users get package faster.

> * accepts .deb directly

AFAIK, no. I assume you meant you make the deb file yourself in your computer then upload? No. You have to upload your deb build script rules files etc... to them. Then their system will build the packages and publish.

> * handles GPG signing natively

As I said in previous, their system will build the package, and it'll be signed via the system too.

> * also supports RPM hosting

Yes, similar to deb, you upload the script for building rpm and their system builds it.

**Comment by shiftkey** [comment]
At this point I don't think I can get this working under OBS - there's too much about the dependencies, toolchain and scripts that I don't think will fit with how OBS does things.
