### ISSUE TITLE
Typescript syntax highlighting breaks under a set of conditions

### ISSUE THREAD

**Issue by khvorov45** [shiftkey/desktop#389]
### Describe the bug

<details>
<summary>Example of wrong highlighting (bottom 3 lines)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102024028-75e8e580-3de3-11eb-969a-2219e071a95b.png"/>
</details>

Most subsequent code would be highlighted in yellow as if it was all a string.

The set of conditions required for this is (images contain (mostly) correct highlighting when the corresponding condition is removed):

<details>
<summary>3+ fields in an object argument</summary>
<img src="https://user-images.githubusercontent.com/44919476/102024146-4b4b5c80-3de4-11eb-9a7d-a7a049cac788.png"/>
<img src="https://user-images.githubusercontent.com/44919476/102024194-a2e9c800-3de4-11eb-8641-7ecef6df5247.png"/>
</details>

<details>
<summary>Generic use in the return type (highlight still questionable without it)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102024224-e17f8280-3de4-11eb-9eac-7799bdc9b408.png"/>
</details>

<details>
<summary>Template string use (highlight still questionable without it)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102024282-3c18de80-3de5-11eb-9057-858f607fb0c9.png"/>
</details>

<details>
<summary>No commas in the types for the object fields (main issue?)</summary>
<img src="https://user-images.githubusercontent.com/44919476/102024353-9f0a7580-3de5-11eb-97f1-57d59e63ede4.png"/>
</details>

### Version & OS

OS: Linux Mint 20
Desktop: 2.5.7-linux1

### Files

[Code in screenshots](https://github.com/shiftkey/desktop/files/5685477/code.tar.gz)

**Comment by shiftkey** [comment]
@khvorov45 thanks for the report. We're using Codemirror and it's syntax highlighting support in GitHub Desktop so maybe something's changed in there.

If this is reproducible on macOS or Windows I think this should be reported on the main repository, as I suspect this isn't a Linux-specific issue at first glance. I'll have a look at reproducing this later in the week when I have some bandwidth.

**Comment by shiftkey** [comment]
Tested this out in macOS with the latest beta release (`2.6.1-beta3`) and I see the same problem as you:

<img width="720" src="https://user-images.githubusercontent.com/359239/102107545-38e31a00-3e08-11eb-8d8f-77560799c891.png">

> No commas in the types for the object fields (main issue?)

There's a sandbox mode for Typescript you can test here https://codemirror.net/mode/javascript/typescript.html which also shows the same behaviour, so I think you're on the right track.

<img width="350" src="https://user-images.githubusercontent.com/359239/102108196-0128a200-3e09-11eb-907c-caca425aad35.png">

~~I can't spot a report in the Codemirror project for this specific issue, but there is a pending update to `codemirror` under `app/package.json` (from `5.49.2` to `5.58.3`) that might address this.~~

EDIT: because we can reproduce this on the Codemirror sandbox, that suggests the latest version of Codemirror doesn't handle this case. That's the place where this needs to be fixed to work correctly in GitHub Desktop.

**Comment by khvorov45** [comment]
Submitted an [issue to Codemirror](https://github.com/codemirror/CodeMirror/issues/6520)

**Comment by khvorov45** [comment]
Fixed in [Codemirror 5.59.0](https://github.com/codemirror/CodeMirror/releases/tag/5.59.0) (not documented in the release notes).
