### ISSUE TITLE
GitHub Links

### ISSUE THREAD

**Issue by Aeirex** [shiftkey/desktop#39]
The Github.com links don't show. I am using Fedora 27.

![screenshot from 2018-04-18 20-13-18](https://user-images.githubusercontent.com/1341321/38965939-331b7042-4345-11e8-8cb0-ee81a7f4b61c.png)

**Comment by shiftkey** [comment]
@Aeirex thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in your File Manager** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by Aeirex** [comment]
I had this happen on Arch Linux as well.

I can't find any logs.

**Comment by shiftkey** [comment]
```
install.ts:23 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
/opt/GitHubDesktop/resources/app/git/libexec/git-core/git-remote-https: /lib64/libcurl-gnutls.so.4: no version information available (required by /opt/GitHubDesktop/resources/app/git/libexec/git-core/git-remote-https)
```

This is likely why Git operations against your private repository are not working. I've found a workaround here for Fedora that might work for you: https://github.com/shiftkey/desktop/issues/21#issuecomment-357715905

There also appear to be some networking errors when interacting with the GitHub API - Desktop needs `libsecret` on Linux to manage credentials, and it's not clear to me whether you have `gnome-keyring` or `kwallet` or neither installed - there's more details over in https://github.com/shiftkey/desktop/issues/7 about this.

**Comment by Aeirex** [comment]
@shiftkey I looked through my logs and see nothing useful. I also have already done this, it is already symbolic linked.

**Comment by Aeirex** [comment]
[2018-0.zip](https://github.com/shiftkey/desktop/files/1985248/2018-0.zip)

**Comment by shiftkey** [comment]
@Helladen thanks for the log - looking at the most recent entry I see you've now got a valid token and can clone things down:

```
2018-05-03T12:28:11.272Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/KDE/kdeconnect-android.git - Aeirex (has token)
```

However I'm still puzzled why private repositories are returning a 404 for you -  we should be using that same token here:

```
2018-05-03T12:28:13.737Z - warn: [ui] fetchRepository: 'HitsparkInteractive/Nin-Online-2.0' returned a 404
```

**Comment by Helladen** [comment]
I got it working after signing out and back in.

**Comment by helladen** [comment]
Update. This bug still happens. I noticed that I can login to my GitHub account, but it only displays website. It doesn't show my private repositories. I also can't pull a repository like I can using bash. It will say I am not authenticated. I even logged out and back in fine. So the problem lies with the authentication system working with the login part.

**Comment by immackay** [comment]
@Aeirex, the AUR package was not updated until today as I've been on vacation. Can you try now and report whether the problem still exists?

**Comment by helladen** [comment]
@immackay I'm using Fedora now. I use Git in terminal to clone and then add it to GitHub Desktop. It doesn't allow me to commit or fetch. I've logged in and out of the client using my GitHub account. It just lacks permissions to do anything.

**Comment by helladen** [comment]
I have private repositories that do not show also.

**Comment by shiftkey** [comment]
@Aeirex are they private GitHub or GitHub Enterprise repositories?

**Comment by helladen** [comment]
https://github.com/HitsparkInteractive

It's not Enterprise, we just pay $25/m for private repositories. This happens on Ubuntu 19.04, too. It seems to be a Linux problem.

**Comment by helladen** [comment]
@shiftkey when I add the Repository it won't let me push it either. It says the repository doesn't exist. Although using Git in the terminal I can pull and push them fine.

**Comment by helladen** [comment]
Still a problem. I am using Ubuntu 18.04.2 and this happens on multiple distros. I have been using SmartGit to pull repos as well as git in the terminal. It does not correctly load the repository though.

![image](https://user-images.githubusercontent.com/1341321/60951216-449aea80-a2be-11e9-8598-51b2b4cd8104.png)

**Comment by shiftkey** [comment]
@Aeirex apologies for the delay in replying.

I believe this is related to organizations restricting access to third party applications, which would block Desktop from being able to push/pull to the repositories belonging to an organization.

This build of the app does not behave the same as the macOS and Windows versions because of #72, and I don't have a timeline on when this will be resolved as it's something that would be part of "official support" by GitHub.

The likely reason this works fine from the command line is because that results in a different way of authentication (i.e. personal access token or basic credentials) that are not tied to an OAuth application.

I know it's been a while, but would you be able to re-test with `2.4.0` and confirm this is the behaviour:

 - able to fetch repositories owned by the user after signing in
 - unable to fetch repositories owned by an organization after signing in

**Comment by helladen** [comment]
It still happens @shiftkey

**Comment by shiftkey** [comment]
@Aeirex thanks for following up.

I'm going to close this out because #72 is the root cause of this behaviour. Please follow along with that issue.
