### ISSUE TITLE
Better sign ins

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#404]
### Describe the feature or problem you’d like to solve
On Chromebook with debian linux, trying to sign in is basically impossible because it says `Chrome OS can't open this page`

### Proposed solution
Something to log in with email and password

### Additional context

![Screenshot 2020-12-30 at 8 49 28 PM](https://user-images.githubusercontent.com/76637506/103390107-9baf0380-4ae0-11eb-8b5f-17500b0886c2.png)

**Comment by shiftkey** [comment]
Please see #138 which has more details about the underlying limitations

> ### Proposed solution
> Something to log in with email and password

This is not feasible due to GitHub API changes related to authorizations. Please see the upstream PR https://github.com/desktop/desktop/pull/11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.
