### ISSUE TITLE
Login does not work on pop_os

### ISSUE THREAD

**Issue by cBodenwinkler** [shiftkey/desktop#414]
### Describe the bug

Login doesn't work with both the app and the 'sign in using your browser' option. Button shows a short load and then stops. Have this problem since I switched to PoP_OS. 
Tried both installing it from the PoPShop and also using terminal - both didn't work.

### Version & OS

Can't open the 'About GitHub Desktop' menu.
Operating System is PoP_OS 20.04. LTS

### Steps to reproduce the behavior

1. Download Github Desktop from PopShop.
2. Enter Email + PW
3. 'Sign in' button shows short load sign
4. Load Sign disappears and nothing happens - No message or anything

### Logs

[2021-01-11.desktop.production.log](https://github.com/shiftkey/desktop/files/5801098/2021-01-11.desktop.production.log)

Thanks for your support.

**Comment by vincnt0** [comment]
Same issue here, updated everything, also tried signing in through the website, that just keeps waiting for a response.

When inspecting with dev tools, there is a "authorizations" request to "https://api.github.com/authorizations" that fails with error 404, returning {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}. 

Kinda confusing, since the server clearly gets reached to return the doc url and message, but still doesn't recognize the request.

Edit: seems like a wide spread issue (see #405 #407 #408 )
Edit 2: This is on version 2.4.1-linux1 for me

Final edit:
So yeah, I installed the newest pre-release version and it works, seems like the version the pop os store is distributing is quite old.
Hope that helps!

**Comment by jonstump** [comment]
I'm having the same issue using the instructions in the readme here on github.

@vincnt0  - how did you install the pre-release version?

**Comment by Mrlinkwii** [comment]
@jonstump 
i think they mean they installed it though  https://github.com/shiftkey/desktop/releases

**Comment by hisra015** [comment]
Also having this issue on Pop! OS

**Comment by vincnt0** [comment]
@hisra015 @jonstump 
As i said the version on the Pop OS store is 2.4.1 which is quite old, I think anything newer than 2.6 should work, just grab one of the latest releases from [the release section](https://github.com/shiftkey/desktop/releases) as @Mrlinkwii mentioned.

I installed the .deb file with Eddy but i would assume any method works.

**Comment by shiftkey** [comment]
> * Enter Email + PW
> * 'Sign in' button shows short load sign

If you're running an old version of GitHub Desktop, please upgrade. There were GitHub API changes related to authorizations which mean username/password authentication is no longer supported. For more context see the upstream PR desktop#11006 and the planned deprecation announcement from late 2019 https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/.

I am not affiliated or responsible for the the Pop!_Shop package, but it needs to be upgraded to at least [`2.6.0-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.0-linux1).
