### ISSUE TITLE
Error 429 Too Many Requests

### ISSUE THREAD

**Issue by migascl** [shiftkey/desktop#419]
### Operating System/Distribution

Ubuntu 20.04

### What happened?

sudo apt-get update fails when fetching from https://packagecloud.io/shoftkey/desktop/any/dists/any/InRelease giving a "429 Too Many Requests"

![vmware_KFiI6DW0ZK](https://user-images.githubusercontent.com/66365138/105422667-0c5ac300-5c3c-11eb-98e7-444cec06e789.png)

**Comment by carstencodes** [comment]
I used to get the same issue (using Linux Mint Ulyssa).

Today the issue is a different one:

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
Reading package lists... Done                                                  
W: GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://packagecloud.io/shiftkey/desktop/any any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by carstencodes** [comment]
The issue seems to be gone.

**Comment by shiftkey** [comment]
#310

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available.
