### ISSUE TITLE
can't log in Fedora 32

### ISSUE THREAD

**Issue by ktdramf** [shiftkey/desktop#450]
### Describe the bug

In the first start, when try to configure the Enterprise account, just pressing the button to go to browser authentication shows the message that the webpage not exist

### Version & OS

Fedora 32, tried with firefox, chrome and brave.
github desktop from packagecloud, appimage and rpm 2.6.3 and 2.6.2

### Steps to reproduce the behavior

1 go to authentication with browser  and got the error.

### Expected behavior

Correct authentication

### Actual behavior

get the "web page not exist" error

**Comment by MonkeySaint** [comment]
Same Issue on Manjaro 20.2.1 also using appimage

**Comment by jamielambrecht** [comment]
I also can't log the AppImage in to GitHub on Solus 4.2 using Firefox 86. At first, I didn't know where the AppImage was so I tried to build it with the dev instructions using yarn, then I found the AppImage. I encountered the same issue on the yarn build:dev, yarn build:prod, and the AppImage versions. The error message I get is as follows:

"The address wasn’t understood
An error occurred during a connection to github.com.
    You might need to install other software to open this address."

**Comment by shiftkey** [comment]
Please refer to #416 for the AppImage issue, which is a known limitation that I'm not sure how to address

> In the first start, when try to configure the Enterprise account,

Logging into a GitHub Enterprise installation is also not supported currently, due to OAuth limitations and this being an unofficial application. https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 is my most recent summary of the situation.
