### ISSUE TITLE
failed to install on debian

### ISSUE THREAD

**Issue by sgehrman** [shiftkey/desktop#471]
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: 54.183.38.243 443]

**Comment by EnzoHB** [comment]
I'm getting the same message on Pop OS. It's really annoying because every time I open Pop Shop It pops an error message saying it failed to update. But It doesn't prevent me from installing and actually, GitHub works just fine.

**Comment by shiftkey** [comment]
This is a PackageCloud behaviour when my account gets suspended due to exceeding the bandwidth I've set. 

The billing cycle resets around the 22nd of each month, and the manual install from the [Releases](https://github.com/shiftkey/desktop/releases) page is still available. But I don't have a workaround for this occurring whenever the client checks for updates.

I initially set this up as a trial to understand this channel of support, but it's clearly at the point where we should re-evaluate this. More details in the tracking issue https://github.com/shiftkey/desktop/issues/278
