### ISSUE TITLE
Fedora 28 KDE: Option to open in GNOME Terminal

### ISSUE THREAD

**Issue by Croydon** [shiftkey/desktop#48]
## Description
While on KDE I see the option "Open in GNOME Terminal" in the repository drop down menu.
Clicking on it results in a error in a popup window: "Cannot read property 'path' of undefined".
I can't see additional information in the developer console.

## Version
* GitHub Desktop: 1.2.0
* Operating system: Fedora 28 KDE

### Expected Behavior
Opens the system console in the git repository directory.

### Actual Behavior
Error: "Cannot read property 'path' of undefined".

### Logs
renderer.js:5 App ready time: 130.8272879999131ms
renderer.js:5 Load time: 1841.185415000189ms
renderer.js:5 Renderer ready time: 1177.47ms
renderer.js:12 launching: 1.2.0 (Linux 4.16.11-300.fc28.x86_64)
renderer.js:12 execPath: '/opt/GitHubDesktop/desktop'

**Comment by Croydon** [comment]
/usr/bin/konsole does exists but it is the KDE Konsole, not the Gnome Terminal.

The options menu within GitHub Desktop actually calls it "Konsole" as well in the drop-down menu to select which console should get used. 

However, the "Open with.." menu point under "Repository" then displays "Open in GNOME Terminal" and the error as reported as above when executed.

**Comment by Croydon** [comment]
@immackay It might be an initial config error, e.g. the value might be wrong when the user never changed the setting (which is not possible when you only see one option displayed).

Somebody wrote somewhere (sorry, not sure where anymore), that after a switch in the option to another selected console and afterwards a switch back the the original desired one it worked.

**Comment by immackay** [comment]
Okay thanks, I'll check out that avenue. 

If I am understanding the error correctly it seems the Shell object that is supposed to be returned by getAvailableShells() is returning null instead, but I'm not sure why - as it should at least resort to Default, which is definitely available at the path defined in linux.ts

I'm not amazing with Typescript, but I'll do my best. Perhaps shiftkey will drop in sometime and offer some light on the issue

**Comment by shiftkey** [comment]
@Croydon are you able to re-test things with a more recent version of the app? I'm wondering if this was a "we don't have any valid shells, but we need to show something" option, and I wonder if this is a non-issue now that we have a more complete set of shells to support.

Otherwise, if this is still occurring, could you please share what list of editors you have under **File** | **Options** and the **Integrations** tab:

![](https://user-images.githubusercontent.com/359239/77830077-bb09a200-7104-11ea-9d08-d474a00e4f93.png)

I only have **GNOME Terminal** but that works because I'm on Ubuntu.



I guess I need to look into improving the tracing in this area, similar to #224, so we can ensure we're able to launch this editor.

**Comment by Croydon** [comment]
I installed 2.4.0 via rpm on Firefox 31 with KDE Plasma 5.17.5 

I was almost reporting that the error is still the same as I got the same result the first time. The second time I opened the settings it finally picked up `Konsole` and removed the `GNome Terminal` from the shell list.

With `Konsole` selected it finally works for me.

Thanks!
