### ISSUE TITLE
change exit shortcut from ALT+F4 to CTRL+Q

### ISSUE THREAD

**Issue by omermecitoglu** [shiftkey/desktop#484]
Imo exit shortcut should be CTRL+Q instead of ALT+F4. Because all other apps in ubuntu are currently using CTRL+Q for quit/exit command.

**Comment by shiftkey** [comment]
Is this a common convention for Linux apps?

The relevant code is this line, so it's an easy change if someone wants to make the change and confirm it works as expected:

https://github.com/shiftkey/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/main-process/menu/build-default-menu.ts#L130-L135

**Comment by omermecitoglu** [comment]
I'm not sure about other distros but it's common in Ubuntu Desktop.

**Comment by zark0-UwU** [comment]
Im not a fan of ubuntu desktop, so firts time i have heard about the shortcut Ctrl+q being used instead of Alt+F4, tho i have tried many distros, never heard of that shortcut being in use, maybe add a config file, for shortcuts or add it as a config box in config inside the program?, willing to help when i get better at typescript

**Comment by kra-mo** [comment]
It is most definitely a common convention. It's standard for both [GNOME](https://developer.gnome.org/hig/reference/keyboard.html) and [KDE](https://docs.kde.org/stable5/en/khelpcenter/fundamentals/kbd.html) apps and most non-native apps like VSCode also support it.

Alf+F4 should be handled by the window manager.
