### ISSUE TITLE
An error occurred during the signature verification

### ISSUE THREAD

**Issue by atorresbr** [shiftkey/desktop#510]
### Describe the bug

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease: 

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F

W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by shiftkey** [comment]
Not sure of what's happened here, but I as this is from PackageCloud there's not much I can do aside from suggest you try again.

I'm thinking of moving away from PackageCloud, please follow along with #278 for the latest...

**Comment by AndreiCherniaev** [comment]
> ### Describe the bug
> 
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease:
> 
> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
> 
> W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
> 
> W: Some index files failed to download. They have been ignored, or old ones used instead.

I want to install github desktop and I use [instruction](https://github.com/shiftkey/desktop)
_# if you want to use packagecloud.io
$ sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'_

And there is t same problem on my Linux 5.4.0-117-generic #132~18.04.1-Ubuntu x86_64 GNU/Linux:
Err:5 http://repo.aptly.info nightly InRelease                                
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EE727D4449467F0E
Hit:7 https://mirror.mwt.me/ghd/deb any InRelease 

I solved it using
_# if you want to use the US mirror
$ sudo sh -c 'echo "deb [arch=amd64] https://mirror.mwt.me/ghd/deb/ any main" > /etc/apt/sources.list.d/packagecloud-shiftkey-desktop.list'_
