### ISSUE TITLE
changing theme needs restart

### ISSUE THREAD

**Issue by ggrrll** [shiftkey/desktop#512]
### Describe the bug

change themes needs restart in order to see change

### Version & OS

* GH D 2.8.1
* Linux mint 20.1
* des env: cinnamon 4.8.6

### Steps to reproduce the behavior

try to change theme from the app settings
 
### Expected behavior

theme should change 'immediatly'

### Actual behavior

in order to see the new theme in place, the app needs to be restared

**Comment by ghost** [comment]
Same for me
 - Fedora 34
 - GNOME 40 (Xorg)

**Comment by shiftkey** [comment]
This is an Electron limitation that I reported upstream back in March https://github.com/electron/electron/issues/25925#issuecomment-796877741 and it seems like it'll be fixed with Electron 13 so I've held off on really digging into this until that's available.

We're also talking about this in #372 and some alternative approaches to improve this support.

**Comment by shiftkey** [comment]
Please test out the [`2.9.9-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.9-linux2) and confirm this is resolved

**Comment by ggrrll** [comment]
:confetti_ball:  :pray:  thank you :)
