### ISSUE TITLE
[Request] Install via Snap Store

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#515]
I install most software via Snap nowadays and am interested in seeing this port to Linux on the Snap store.

Since `electron-builder` is found in the __package.json__ file, this should be easy to do, as Electron Builder does support .snap files.

**Comment by shiftkey** [comment]
I originally had this working but had to back it out because an upgrade to the docker environment it runs in resulted in a broken installer #163. I'm tracking this in #202 but I haven't picked it up again because the overall experience was much more convoluted than the other installers.

Please get involved with that discussion if you want to see this supported again.
