### ISSUE TITLE
I can't see all remote branch

### ISSUE THREAD

**Issue by formation2020** [shiftkey/desktop#531]
### Describe the bug

I can't see all my remote branch.

with command line, i see some remote branch wich are not in githubdesktop

### Version & OS

Ubuntu 18.04.5 LTS

### Steps to reproduce the behavior

1. Go to 'Current branch menu.'
2. Click on ' text area and tape the name of some remote branch.'

### Expected behavior
3.the result of this filter should be ok

### Actual behavior
3.  i don't see the searched remote branch

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/70441597/122453319-222da380-cfa2-11eb-87fb-04b5c5d7595d.png)

![image](https://user-images.githubusercontent.com/70441597/122454744-9ae12f80-cfa3-11eb-86cf-0fdf28aebf88.png)

**Comment by Mrlinkwii** [comment]
which version of github desktop sorry ? :confused:

**Comment by shiftkey** [comment]
@formation2020 thanks for the report. Based on the screenshot what I think is happening here is:

 - you're currently on `test/page`, which I suspect is tracking `origin/test/page`
 - GitHub Desktop won't show the remote branch when you have a local branch that tracks it, to avoid "I want to be on my remote branch" confusion when you need to be on a local branch that tracks the remote branch
 - due to this reasoning, filtering on `origin/test` won't show the branch

https://github.com/shiftkey/desktop/blob/51ff60477f199e0c15ab8d35eff78d90dc63feb1/app/src/lib/stores/git-store.ts#L431-L440

 - the list of branches is populated using `git for-each-ref [options] refs/heads refs/remotes` which is slightly different to `git branch` and allows better control of the output that Desktop needs

https://github.com/shiftkey/desktop/blob/51ff60477f199e0c15ab8d35eff78d90dc63feb1/app/src/lib/git/for-each-ref.ts#L14-L39

 - selecting a remote branch will result in creating a local branch which tracks that remote branch, because that's what Git requires to avoid a "detached HEAD" scenario

I'm going to close this out as it's a product decision with a lot of context, but happy to answer any extra questions you might have in this area...
