### ISSUE TITLE
White window when starting application v2.9.0

### ISSUE THREAD

**Issue by PaulAtST** [shiftkey/desktop#533]
### Description

When starting the application no UI is loaded, all I get is a white window.

### Version & OS

Version: GitHubDesktop-linux-2.9.0-linux1.deb
OS: Ubuntu 20.04 running on Parallels Desktop 16

### Steps to reproduce the behavior

1. Open application
2. All white window with no UI opens

### Expected behavior

Github desktop UI should load

### Actual behavior

All white window with no UI opens

### Screenshots

![Screen Shot 2021-06-18 at 2 50 00 PM](https://user-images.githubusercontent.com/66137501/122604763-7ee19a80-d044-11eb-9f11-e50ac126aa28.png)

### Additional context

I also tried opening the application from terminal, and from terminal with `--disable-gpu` with no luck. I see the exact same behavior each time.

**Comment by shiftkey** [comment]
Try setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to some value, which should trip this path and signal to the Electron runtime to disable hardware accelerated rendering:

https://github.com/shiftkey/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/main-process/main.ts#L265-L270

**Comment by PaulAtST** [comment]
@shiftkey That worked. Thank you!

I wonder if this should get added to the readme since gpu acceleration in electron and virtual machines don't usually play nice together. Also the `--disable-gpu` flag not working, makes it cryptic.

**Comment by shiftkey** [comment]
I've linked to the Known issues doc in the [README](https://github.com/shiftkey/desktop#known-issues) to follow the pattern for other platforms, and [this issue is now documented](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-get-a-white-screen-when-launching-desktop).

> Also the `--disable-gpu` flag not working, makes it cryptic.

This hasn't been supported because we have plenty of usage that isn't launched from a terminal, and environment variables are available to all OSes, which is how we settled on this.

For reference, you can see the CLI arguments that Desktop supports by adding `--help`:

```
$ github --help
Commands:
  clone <url|slug>  Clone a repository                       
  help [command]    Show the help page for a command         
  open <path>       Open a git repository in GitHub Desktop  

Run github help <command> for details about each command
```

The main `github-desktop` program does support some Electron arguments, but is very much not recommended for most users.

**Comment by PaulAtST** [comment]
@shiftkey Makes sense, thanks again for the help!
