### ISSUE TITLE
Possibility of cross-package support for app data?

### ISSUE THREAD

**Issue by K0-RR** [shiftkey/desktop#584]
I wanted to switch to the flatpak version but noticed it does not detect already used/downloaded (by the deb version) repositories. Maybe it can detect them and symlink or ask the user if they want to move them? 
Yeah, the title sucks. I would be happy if someone renamed it.

**Comment by shiftkey** [comment]
@RDKRACZ great question, and the devil is in the details.

On Linux the application data for GitHub Desktop is stored within the `~/.config/` directory, in an application-specific path. The [Electron docs](https://www.electronjs.org/docs/latest/api/app#appgetpathname) explain the various options available to app developers.

GitHub Desktop however uses IndexedDB within Chromium to store much of the various app data it needs:

 - local repositories
 - GitHub user, issue and pull request data
 - other GitHub metadata

I think we settled on this early on because it saved us from having to implement our own relational database as well as all of the quirks that come with building a robust relational database from scratch (handling schema updates and transactions, as well as the actual work for storing and retrieving data).

Here's a couple of examples of the components:

 - [`RepositoriesDatabase`](https://github.com/shiftkey/desktop/blob/c04d1aeb46aa87953531aa83ce96d1c120281b21/app/src/lib/databases/repositories-database.ts#L71)
 - [`RepositoriesStore`](https://github.com/shiftkey/desktop/blob/c04d1aeb46aa87953531aa83ce96d1c120281b21/app/src/lib/stores/repositories-store.ts#L29)

So while these files are located at `~/.config/GitHub Desktop/IndexedDB/` when using the DEB installer I don't believe these are able to be shared with the flatpak installer (which is likely to be installing itself elsewhere because of the sandboxed nature of these apps).

**Comment by shiftkey** [comment]
Closing this out as I don't have bandwidth to support this, and it's not clear how much value there is long-term to support both environments.

If someone wanted to experiment here I'd look at [`app.setPath`](https://www.electronjs.org/docs/latest/api/app#appsetpathname-path) as a way to change at runtime the `appData` directory instead of trying the symlink/migration path.

Outstanding questions I have aside from the approach:

 - Can the flatpak build access arbitrary paths under `~/.config`? Or does that need to be manually set by the user?
 - What happens if you jump back and forth between the flatpak and deb/RPM builds? Which one is the source of truth?
 - What happens if the Electron versions gets out of sync between the two installs? I've had some anecdotes of data loss because Electron tries to use a older version of Chromium with a newer data directory format while developing, so I worry about connecting these up arbitrarily.
