### ISSUE TITLE
Support fractional scaling

### ISSUE THREAD

**Issue by keunes** [shiftkey/desktop#591]
### Describe the feature or problem you’d like to solve

Currently, the screen is blurry when I enable 'fractional scaling' on my system.

### Proposed solution

Support fractional scaling :-)

### Additional context

Not sure if you can do anything about this, or if I should report it upstream?

Many thanks for making GH Desktop available to us!

**Comment by shiftkey** [comment]
I'm not even sure where to start - what details can you share about your setup and window manager?

**Comment by keunes** [comment]
Not much, as it's quite default: fresh Ubuntu 21.04, should've mentioned that, sorry. After installing GH Desktop via the PPA, I activated fractional scaling on the device (a Microsoft Surface Pro 2) and set it to 125%.

No idea what window manager Ubuntu comes with, to be honest.

**Comment by shiftkey** [comment]
I believe Ubuntu 21.04 uses Wayland as it's default display server, and I ask because Electron 12 and later has better Wayland support (Chromium mentions a thing called [Ozone](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md) and https://github.com/electron/electron/issues/10915 mentions how Electron started on support for it).

The upstream team are looking at upgrading GitHub Desktop from Electron v11 (latest version is v13) and once they're feeling confident in the upgrade I'll see if there's any upgrade pain on our end with these new changes...

**Comment by vchernin** [comment]
Some further info:

The root issue here is that apps running in Xwayland (currently all Electron releases _by default_) are not able to adjust correctly when fractionally scaling in Wayland.

Running in Wayland _natively_ resolves this since there's no more Xwayland (as mentioned this is possible with Electron 12 or newer). Still the Xwayland issue might be resolved in the future such that Xwayland can fractionally scale properly https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733.

Also, while running in Wayland will solve the fractional scaling issue, unfortunately on Ubuntu you will notice there are no title bar (eg. you can't drag the window around nor use the close button). Luckily this will be solved by https://github.com/electron/electron/pull/29618, and this is all upstream so there isn't much to do here with shiftkey either.

**Comment by keunes** [comment]
Thanks @vchernin for chipping in. So if I understand correctly
1. first the electron PR needs merging
2. then Electron needs to switch to Wayland as a default (or shiftkey could switch over to Wayland for this project)

Did I understand correctly?

**Comment by vchernin** [comment]
> first the electron PR needs merging

That PR is only relevant if want the title bar to be present. The app will be able to run in Wayland natively regardless (once it’s on Electron 12 or newer).

As a sidenote the title bar issue will only occur on GNOME which Ubuntu uses, but not on KDE/Sway. And you can use keyboard shortcuts to workaround the lack of title bar.

> then Electron needs to switch to Wayland as a default (or shiftkey could switch over to Wayland for this project)

There is no need to wait for Electron to switch its default. Once Electron is 12 or newer users can opt in to native Wayland by passing `--enable-features=UseOzonePlatform --ozone-platform=wayland` at runtime. You can also set these at build time (but until the title bar issue is fixed I wouldn’t recommend it).

Electron will very likely follow Chromium here, when Chromium runs in Wayland by default Electron will too (it’s progressing but it might still be a few releases before it’s default).

**Comment by keunes** [comment]
Thanks again :)

> As a sidenote the title bar issue will only occur on GNOME which Ubuntu uses, but not on KDE/Sway. And you can use keyboard shortcuts to workaround the lack of title bar.

As I'm on Ubuntu and wouldn't really want to work without title bar, I'll rather wait a bit :)

**Comment by red5h4d0w** [comment]
I wanted to know if there was any updates on this. Is there a branch with a newer electron or something?
I tried to pass --enable-features and --ozone-platform, but the app always crashes on launch. I can go without a title bar but can't go with crashes.
On Endeavour OS / AUR / Gnome-mutter Wayland using 125% (fractional) scaling

**Comment by shiftkey** [comment]
> I wanted to know if there was any updates on this. Is there a branch with a newer electron or something?

Not currently, but I have my eye on https://github.com/desktop/desktop/pull/13689 as the upstream project is handling the upgrade process to Electron 14.

**Comment by vchernin** [comment]
FYI that upstream title bar fix https://github.com/electron/electron/pull/29618 was merged, but that will probably only make it in Electron ~18. At least with 14 it should be fairly usable.

**Comment by red5h4d0w** [comment]
Thank for the info
Good to know that the upstream upgrade to Electron 14 seems to be coming soon!

**Comment by shiftkey** [comment]
The main project has updated to Electron 16 and 17 last week, so I have a build out that should address this - [`2.9.9-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.9-linux1). Please test this out and confirm we're good to close this out.

**Comment by red5h4d0w** [comment]
I was able to run the .appimage for the 2.9.9 RC on wayland with frational scaling with
`path_to_app_image --enable-features=UseOzonePlatform --ozone-platform=wayland`
So it works!
However, the title bar is missing, but I believe wayland titlebars are a very recent improvement to electron. But this is not the same issue as supporting wayland

**Comment by vchernin** [comment]
You should only need `path_to_appimage --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto` on Electron 17 or later.

Setting ozone platform hint to auto is better since it should still work on X11.

**Comment by red5h4d0w** [comment]
running `path_to_appimage --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto` seems to make the app run on XWayland, but I was able to get both wayland and the title bar with `path_to_appimage --enable-features=WaylandWindowDecorations --ozone-platform=wayland`

(Checked that it was XWayland using xwininfo)

**Comment by vchernin** [comment]
Does `echo $XDG_SESSION_TYPE` output `wayland`? I believe that’s what ozone platform hint auto uses.

**Comment by red5h4d0w** [comment]
It outputs wayland as expected.

**Comment by shiftkey** [comment]
It's been almost a year since the last comment on this thread and without any new discussion about it (we're now on Electron 19, and 22 is going to be the next bump) I'm going to close this out as out of date.

If you have any extra details about this area, please open a fresh issue so we can discuss further.

**Comment by red5h4d0w** [comment]
Fractional support currently works on Wayland and has worked under Wayland for a while now so I also think it's fair to close this.
