### ISSUE TITLE
[Electron] fails to launch with "GPU process isn't usable. Goodbye." error message

### ISSUE THREAD

**Issue by maxdraki** [shiftkey/desktop#604]
### Describe the bug
GitHub fails to launch with `FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.` on Ubuntu 21.10 beta

### Version & OS
version GitHubDesktop-linux-2.9.3-linux1

Distributor ID:	Ubuntu
Description:	Ubuntu Impish Indri (development branch)
Release:	21.10
Codename:	impish

Linux 5.13.0-16-generic

### Steps to reproduce the behavior

Fails to launch from dash - launching from CLI gives this error ^

LMK if you need more information

**Comment by maxdraki** [comment]
I think - could be wrong - that it's related to this - https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468
`github-desktop --no-sandbox` works fine (phew)

**Comment by shiftkey** [comment]
> It's due to the new glibc, confirmed using vscode
>
> Dylan, looks like Electron 14+ has the fix.

Thanks for digging up that thread @maxdraki. Looks like we'll need to revisit this after upgrading to a more recent version of Electron...

**Comment by K0-RR** [comment]
Same on openSUSE Tumbleweed.
```
[14506:1209/161626.802346:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
GitHubDesktop-linux-2.9.4-linux1

**Comment by shiftkey** [comment]
After https://github.com/desktop/desktop/pull/13689 was landed upstream in readiness for Electron 14 with the next release I took the opportunity to test the Linux build with the latest round of distros:

### Fedora 35

<img width="1674" src="https://user-images.githubusercontent.com/359239/152657235-84b0248d-214c-438d-ac7f-9e573ed96f5a.png">

### Ubuntu 21.10

<img width="1672"  src="https://user-images.githubusercontent.com/359239/152657425-0d9b422e-83e0-4990-b78f-96d021ad1ae5.png">


There's a significant batch of changes coming up, but hopefully once the official release is out I'll cut a release for this repository so that others can start testing with their own setup:

https://github.com/shiftkey/desktop/blob/df1e34178cef87f657f377608e76ad768d79cd00/changelog.json#L3-L18

**Comment by shiftkey** [comment]
The main project has updated to Electron 16 and 17 last week, so I have a build out that should address this - [`2.9.9-linux1`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.9-linux1). Please test this out and confirm we're good to close this out.
