### ISSUE TITLE
`github .` from the command line doesn't add the current folder as a repository on first launch

### ISSUE THREAD

**Issue by MaddyGuthridge** [shiftkey/desktop#620]
### Describe the bug
As per https://github.com/desktop/desktop/issues/13220 running `github .` from the terminal should open the current folder as a repo.

### Version & OS

OS: Manjaro Linux Stable, KDE Plasma 5.22.5. 
GitHub Desktop version: 2.9.4-linux1

### Steps to reproduce the behavior

1. In a terminal, CD to some repository that hasn't been added to GitHub desktop
2. Run `github .` or `github-desktop .` (I had to do the latter but it's supposed to be the former)
3. Observe that GitHub Desktop launches
4. See that the current folder has not been added

### Expected behavior

The folder is added as a repository

### Actual behavior

The app launches but takes no action

**Comment by shiftkey** [comment]
:wave: thanks for the report!

It's been a while since I've been in this area, but here's the bits I'm spelunking:

https://github.com/shiftkey/desktop/blob/0e80de1fc665f2187f90d740487939aaf2816d8a/app/static/linux/github

This is the script that we add to the PATH and this should go through.

But we have multiple commands available in the main app, which are visible when you run `github --help`:

```
$ github --help
Commands:
  clone <url|slug>  Clone a repository                       
  help [command]    Show the help page for a command         
  open <path>       Open a git repository in GitHub Desktop  

Run github help <command> for details about each command
```

https://github.com/shiftkey/desktop/blob/0e80de1fc665f2187f90d740487939aaf2816d8a/app/src/cli/commands/open.ts

This is the "open" command that is listed above.

So `github open [path]` works for me:

 - if the directory is already in the app, it selects it in the app
 - if the directory is not tracked, the "Add local repository" dialog is shown

Kinda puzzled about this `github .` case, will have to check the other platforms - perhaps we need to special-case is in the `github` script? 🤷🏻

**Comment by shiftkey** [comment]
After doing a side-by-side with macOS I think I've isolated the problem case:

### macOS

 - application _not_ running + `github .` -> app opens, shows "Add Local Repository" message ✅ 
 - application running + `github .` -> app gains focus, shows "Add Local Repository" message ✅ 

### Ubuntu (with 2.9.6)

 - application _not_ running + `github .` -> app opens, does not show "Add Local Repository" message ❌ 
 - application running + `github .` -> app gains focus, shows "Add Local Repository" message ✅ 

@MiguelGuthridge not sure when I'll get to the root of this one but I figured I'd post this context and see if it helps someone dig into it further. It's good to know it works _sometimes_here so it should be a supported flow.

**Comment by MaddyGuthridge** [comment]
It's good to know that there's a reasonably simple workaround at least! Thanks for the investigation :)

**Comment by sarim** [comment]
> ### Ubuntu (with 2.9.6)
> * application _not_ running + `github .` -> app opens, does not show "Add Local Repository" message ❌
> * application running + `github .` -> app gains focus, shows "Add Local Repository" message ✅

https://github.com/shiftkey/desktop/blob/b4dd5c72825b9fdcafa000da9fb53511fa4c7a90/app/src/main-process/main.ts#L156
So, I did a deep dive, The function responsible for this is `handleAppURL`. For mac its being called from `'open-url'` event handler, that's why it gets called for both first launch and subsequent launches. It's a mac only event.

For linux it gets called from `handlePossibleProtocolLauncherArgs` function. But `handlePossibleProtocolLauncherArgs` function only gets called from `'second-instance'` event handler. Thats why it works only for subsequent launches. I added another ***if linux** block to call it at first launch too. PR opened.


A second kinda relevant issue is if your project folder's name is "github-desktop", it won't automatically open by github command. Thats because of this
https://github.com/shiftkey/desktop/blob/b4dd5c72825b9fdcafa000da9fb53511fa4c7a90/app/src/main-process/main.ts#L274-L278
It's there to clean `/usr/lib/github-desktop/github-desktop` from arg list, but if your project folder is github-desktop, and it gets passed as `x-github-client://openLocalRepo/%2Fhome%2Fgittu%2Fgithub-desktop`, and it gets cleaned up too. I can fix it with a regex, will open another issue/PR after this one gets merged.
