### ISSUE TITLE
Installation in Readme not working

### ISSUE THREAD

**Issue by keunes** [shiftkey/desktop#631]
Hello,

I used `wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo tee /etc/apt/trusted.gpg.d/shiftkey-desktop.asc > /dev/null` to install GitHub Desktop.

But the terminal got 'stuck' (no output, no ending of task until hitting ctrl+c). Removing `-qO` helped -- is that O supposed to be there?

**Comment by shiftkey** [comment]
@keunes thanks for the report!

The `-q` parameter here is to run wget in quiet mode, so that no additional output is piped into the next command. And I believe `-O` is here to support shell redirection, so it's probably important:

```
Use of -O is not intended to mean simply "use the name file instead of the one in the URL;" rather, it is analogous to shell
redirection: wget -O file http://foo is intended to work like wget -O - http://foo > file; file will be truncated immediately, and all
downloaded content will be written there.
```
>  From https://askubuntu.com/a/655707

The request getting stuck could suggest an intermittent issue with the server fetching the GPG key, but that's just a guess.

Glad you were able to get around it, I'm going to close this out as I think both of these parameters are needed to flow this GPG key to the right place on disk...
