### ISSUE TITLE
adjust minimum height/width constraints for smaller screen sizes

### ISSUE THREAD

**Issue by ipkpjersi** [shiftkey/desktop#65]
## Description

I believe the minimum height is too large for my setup and causes the GitHub Desktop to open up with maximum height on the wrong monitor.

## Version

* GitHub Desktop: 1.4.0-linux2 (also happened on 1.3.x and earlier) snap

* Operating system: Ubuntu 16.04 with Xfce 4.12

## Steps to Reproduce

1. `Open GitHub desktop on Ubuntu 16.04 Xfce 4.12 with a 768p screen with a 48 pixel tall bottom panel/bar/dock and a 30 pixel tall top panel/bar/dock (whatever you want to call it)`
2. `It now opens on my second monitor (a 1080p screen)`
### Expected Behavior

I expect it to open minimum size for height and width as it does on two 1080p monitors.
### Actual Behavior

The minimum height of GitHub desktop is too large. Is there any way to decrease the minimum height - even if just for the Linux port, or maybe upstream? Or, perhaps fixing it so that it opens with the correct minimum height on my second monitor? I am not sure if this issue belongs upstream or in the Linux port.

Keep in mind, when I launch GitHub desktop with my mouse on my second (1080p) screen, the minimum height and width are what they should be - it is only when I keep my mouse on my primary (768p) screen that the height becomes maximum.

Sorry for my very strange use-case, but, these things happen in life.

Here are some (horizontally cropped to redact info) pictures that show what I am talking about.

Here is an example of the issue I am talking about:
![screenshot](https://user-images.githubusercontent.com/33754783/45644481-d3b6e780-ba8b-11e8-9183-57e1ef4abc6b.png)

Here is what it should look like: 
![screenshot2](https://user-images.githubusercontent.com/33754783/45644559-ffd26880-ba8b-11e8-9dff-6833029eb0ac.png)

Notice the 713px height instead of the 1080px height.

**Comment by asianjakepaul** [comment]
Have you tried to reproduce this issue with different electron based applications like atom?

**Comment by ipkpjersi** [comment]
I have not. However, this is only really particularly an issue for me on GitHub Desktop as I start Atom maximized.

**Comment by asianjakepaul** [comment]
Can you test this with atom, I doubt this is an issue in github desktop but more like an electron issue or even your desktop environment / window manager.

**Comment by ipkpjersi** [comment]
I am not sure if I will be able to effectively test this with Atom - Atom doesn't have a minimum size like GitHub Desktop does - if GitHub Desktop reduced the minimum size (or removed it altogether) - it would solve this issue for me entirely, since it would likely fit on my second monitor and I believe this would not be an issue anymore.

**Comment by asianjakepaul** [comment]
I didn't notice github desktop always starts with a height of 960px, It looks like there is an API for getting primary screen size, not sure if this should only be in the linux fork.

https://github.com/electron/electron/blob/master/docs/api/screen.md

**Comment by shiftkey** [comment]
The relevant parts to this issue...

- We set an absolute minimum height and width for Desktop here:

https://github.com/shiftkey/desktop/blob/a0e25e0c95db5e475b126735236d309a18e3d2dc/app/src/main-process/app-window.ts#L21-L22

- We combine this with the remembered values from `electron-window-state`:

https://github.com/shiftkey/desktop/blob/a0e25e0c95db5e475b126735236d309a18e3d2dc/app/src/main-process/app-window.ts#L32-L35

 - These are then provided to the Electron `BrowserWindow` constructor:

https://github.com/shiftkey/desktop/blob/a0e25e0c95db5e475b126735236d309a18e3d2dc/app/src/main-process/app-window.ts#L37-L56

The last time I looked at these values it was related to https://github.com/desktop/desktop/issues/4320#issuecomment-376001239 which was in reference to Aero Snap on Windows (which lets you easily move a window to a quarter of the screen) and we talked about the downsides of just relaxing this constraint here: https://github.com/desktop/desktop/issues/1702#issuecomment-312952005

**Comment by ipkpjersi** [comment]
@asianjakepaul The app does launch with the last window state - the problem is, with the minimum height being set to what it is, I can't set it to small enough that it doesn't cause this issue.

**Comment by MPLew-is** [comment]
As another use case that is currently being prevented by the sizing being what it is, it's difficult to use the app on a MacBook Pro 13" with effective resolution of 1680x1050; I would prefer to have my screen split to left and right halves, meaning I would want GitHub Desktop to be 840 pixels wide, which is prevented by the current configuration.

**Comment by shiftkey** [comment]
> @shiftkey Is this something you might be willing to fix? 

@ipkpjersi changing numbers around isn't hard, but I don't really have the bandwidth or right setup to dig into this currently. I'd love for someone who is actually feeling this pain to dig into it and suggest a way forward.

I'll also call out this comment from https://github.com/desktop/desktop/issues/1702

> While I could see us perhaps allowing a slightly lower minimum height (say ~600) the current values were definitely chosen deliberately to work on the absolute majority of our users screens while guaranteeing us the screen real-estate we need and are going to need for the features we're planning.

So what I'd love to see from someone affected by this issue:

 - propose a new minimum height/width default for the app, and how you came to that conclusion
 - build the app from source with these new values. [The setup instructions](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md) will help with this.
 - testing out locally what the app looks like at this new minimum size in the changes tab (so you see the list of files and the diff). Does that feel like enough space for the app? Can you share a screenshot or two of things so others can follow along?
 - test out the app in the history view when comparing a feature branch to your default branch. Again, does it feel like there's enough space? Can you share some screenshots too?

Rather than just changing values and having to go through lots of testing to uncover the impact, having someone do this now will give us an idea of the overall impact to reducing the minimum dimensions of the app. And if we feel like shipping some Linux-specific builds to test this we can do this out of band and get even more insight before we take this upstream.

**Comment by bb441db** [comment]
I think we should just omit this line https://github.com/shiftkey/desktop/blob/6621825c3de8f6edff4f68574ce3658a6e48c91e/app/src/main-process/app-window.ts#L43 it will still launch with a height of `660`, but users are at least able to resize the window to something that fits their screen (right now its 660 not resizable).

**Comment by ipkpjersi** [comment]
That seems like a great idea, making it resizeable would fix this issue because then I could resize it to below the minimum height and then it would save that height - which would fix the problem.
