### ISSUE TITLE
Nao estar carregando... no linux Ubutun

### ISSUE THREAD

**Issue by ElmoBraun** [shiftkey/desktop#678]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
Please submit a new report with more information, as it's not clear to me which versions of tools you are using.

Please also locate the log files from the **Help** | **Show logs in your File Manager** menu item and include a recent log from when this problem was occurring. 

Without more information about the underlying error I suspect this is a generic issue with the app not being able to store the token from the OAuth signin flow on your local machine...
