### ISSUE TITLE
Show Repos' from Organizations you own or are a member of

### ISSUE THREAD

**Issue by Whats-A-MattR** [shiftkey/desktop#693]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

Replication of feature from Windows App. 
When logged in with GitHub Auth on the Windows App, repositories are available from any Orgs you have access to. 
Would be great to have this in the Linux version too. 

### Proposed solution

Allows for smoother use of the application, removing the need to manage additional credentials.

**Comment by shiftkey** [comment]
This is a [known issue](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization) due to being a fork of the upstream project:

> ## I cannot access repositories under my organization
> 
> The GitHub Desktop application is an OAuth application, but this fork does not
> have the same permissions as the app does on Windows and macOS, which manifests
> in a couple of different ways:
> 
>  - the "Clone a Repository" view does not show all organization repositories
>  - pushes to a repository owned by an organization may be rejected with a
>    generic error message
> 
> The root cause of this is organizations by default will have "OAuth App access
> restrictions" enabled, which blocks the GitHub Desktop development app that is
> used by this fork.
> 
> **Workaround:** ask your organization admin to [approve access](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/approving-oauth-apps-for-your-organization)
> to the GitHub Desktop development app.

Unfortunately the work required to improve this experience isn't straightforward. Please follow along with https://github.com/shiftkey/desktop/issues/72 which is tracking the underlying issue here.
