### ISSUE TITLE
Flatpak VSCode is not resolved as valid external editor

### ISSUE THREAD

**Issue by DexterUp** [shiftkey/desktop#701]
### Operating System/Distribution

Which distribution of Linux are you using?
Mint 20.3
### Installer

Which version of the app?
Which installer type?
last
### What happened?
Github desktop no indentify a flatpak visual studio code version 1.66.1
Provide as much detail as possible. Error messages or output are extremely useful.

**Comment by shiftkey** [comment]
These are the VSCode paths that the app looks for:

https://github.com/shiftkey/desktop/blob/19e7cd4c28f48ee8a1faf22050661c60334d02c6/app/src/lib/editors/linux.ts#L27-L41

There's probably some `/var/lib/flatpak/` path here that needs to be added

**Comment by DexterUp** [comment]
Thank you, it's working.

**Comment by tommerty** [comment]
Hey @DexterUp and @shiftkey, hoping to re-open this or discuss more if that's ok. Could I get a better explanation on how to resolve?

I have `code-insiders` inside my `/usr/bin/` directory, I'm just not sure what you mean when you say:

>There's probably some /var/lib/flatpak/ path here that needs to be added

Using Fedora 38, and I'm also a bit of a noob with the Linux filesystem

EDIT: Solved it by following the official install rather than downloading from Flathub
