### ISSUE TITLE
Unable to clone repository form Desktop Github app on Ubuntu

### ISSUE THREAD

**Issue by ShrutikaGvsu** [shiftkey/desktop#746]
I can clone the repo on my terminal, but unable to do so in the Github Desktop app

OS: Ubuntu 22
Github Desktop: 3.0.3-linux-1
Additionally, I cannot see the Github Desktop link on my browser under the clone icon

**Comment by shiftkey** [comment]
The error from the logs suggests that a `gh` command was used for input, which isn't understood by the application:

```
2022-08-01T18:25:34.075Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- gh repo clone GVSU-Enterprise-Applications/coldfusion-docker /home/shrutika/Documents/GitHub/coldfusion-docker` exited with an unexpected code: 128.
stderr:
fatal: repository 'gh repo clone GVSU-Enterprise-Applications/coldfusion-docker' does not exist
```

You can add the existing repository to the app using the **File** | **Add local repository** menu item, or you can use the **File** | **Clone repository** command - this will accept the `HTTPS` url or the `owner/name` shorthand:

![](https://user-images.githubusercontent.com/359239/182430627-c474f5b6-a4fd-4784-af8c-f47c1332e421.png)

> Additionally, I cannot see the Github Desktop link on my browser under the clone icon

Please see #131 for more context, as this is not officially supported currently.

**Comment by KrisBhatt22** [comment]
Hi, I have installed Ubuntu 22 in my system yesterday and I was also facing the similar issue with Github Desktop. As per the recent changes in Github policy, cloning repository from an organization or private repository password authentication will not work as it has been closed on Aug 13, 2022. So, in order to close the repo, use SSH URL for cloning the repo.
