### ISSUE TITLE
Can't clone from URL using Linux GitHub desktop

### ISSUE THREAD

**Issue by LaneSnively** [shiftkey/desktop#758]
### The problem

I cannot clone a repository from URL using GitHub desktop for Linux. I can do this operation for the same URL repository using GitHub desktop for Windows. I successfully cloned the repository from URL using Git command line interface. I've seen other people post the exact same issue on the internet from 2021 and it is still not working in 2022. 

### Release version

Version 3.0.5-linux1 (x64)

### Operating system

Ubuntu 22.04.1 LTS

### Steps to reproduce the behavior

Using GitHub desktop
Clone repository using URL
Enter username and passphrase (I used a personal access token)
unauthorized

### Screenshots

![Screenshot from 2022-08-31 14-34-25](https://user-images.githubusercontent.com/47125744/187777429-3e579df7-08d1-4852-8980-968da62fc09d.png)

### Additional context

(https://github.com/desktop/desktop/issues/13131)
This is a report about the exact problem where users experience the same issues in the same environment.

**Comment by robinpecha** [comment]
Same problem, and I cannot fetch existing one. Only repos in my account works, all where Im added as colaborator fails. It even do not appear in list.

**Comment by ale0790** [comment]
same problem

**Comment by kanekyas** [comment]
Think it's a git command line issue.(linux + two factor personal token)

Sorry for the Japanese screen...

Then, Windows(No problem)
![WS000003 JPG](https://user-images.githubusercontent.com/108772339/191477846-a7334e4d-a976-4f9b-9f82-dbd8dcaef0ce.png)

Then, Ubuntu(Fails if you do not include a personal token in your username)
![WS000002](https://user-images.githubusercontent.com/108772339/191477858-80cfdfe5-af3b-4325-846c-d92e5a66eefc.png)

**Comment by yasuking0304** [comment]
This can be avoided (the problem is the git command).

The essential resolution request is:
https://gitgitgadget.github.io
or
https://github.com/git/git

---
0. example) parsonal token is:ghp_ZXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1e
1. Copy repository url.
![Screenshot from 2022-09-26 10-49-15](https://user-images.githubusercontent.com/111163564/192179314-14ccd531-c390-48d5-8e3c-b2e9c9d79a09.png)

2. add parsonal token
https://github.com/yasuking0304/desktop.git
⬇
https://ghp_ZXXXXXXXXXXXXXXXXXXXXXXXXXXXXX1e@github.com/yasuking0304/desktop.git

3. paste to "clone a repository dialog"
![Screenshot from 2022-09-26 10-51-03](https://user-images.githubusercontent.com/111163564/192179484-3b202c7b-11e6-4d7d-9a35-489f577795bd.png)

**Comment by shiftkey** [comment]
@LaneSnively @robinpecha @ale0790 if you could share a recent logfile from `~/.config/GitHub Desktop/` when you see this problem there may be more information about why this is failing to work for you...

**Comment by yugandhar-btc** [comment]
Same problem
