### ISSUE TITLE
Exiting GPU process due to errors during initialization

### ISSUE THREAD

**Issue by gkamendje73** [shiftkey/desktop#792]
### The problem

I just installed version 3.1.1 and I am getting the following errors when starting from the command line. (The application won't start from the menu entry. 
```
github-desktop 
[14111:1108/020940.991738:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[14146:1108/020941.077805:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

### Release version

3.1.1

### Operating system

Redhat EL7

### Steps to reproduce the behavior

Download the rpm
Install the rpm using rpm -i
Launch the application using github-desktop from the command line. 

### Log files

[2022-11-08.desktop.production.log](https://github.com/shiftkey/desktop/files/9958674/2022-11-08.desktop.production.log)

**Comment by Kalitsune** [comment]
Hello, GPU errors are common issues with electron application.
Does running 
```
github desktop --disable-gpu
``` 
helps by any chance?

if not so, could you please share more information about your graphical environment (windowing system, graphic card vendor, etc...)?

**Comment by gkamendje73** [comment]
Hello, 
Thanks for the hint. That fixes the problem and I am able to access my github account. Any idea why I am still getting the error bellow despite disabling the GPU? 
```
github-desktop --disable-gpu
[18631:1111/093415.480374:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by Kalitsune** [comment]
Well, it seems like your GPU driver doesn't support dri3 (which is an object provided by X11 to help building rendering libraries), if you want to fix it you should try updating your GPU driver 😅

**Comment by gkamendje73** [comment]
Thank for the hint. I am running on a virtual machine hosted in the cloud. Not sure I fully master the GPU configuration. Given that I am passing the `--disable-gpu` option, shouldn't any GPU related stuff be disabled as well?

**Comment by Kalitsune** [comment]
I'm not really sure of what exactly is happening but it seems that the error is coming from x11 which I'm not exactly sure of how it works.

But it may be because the error happens during the init before disabling the gpu or it may be because the app isn't using the gpu but the global x11 windowing system may still be? I'm not an expert, those are just hypothesis.  

Anyway if it works it's not really important as electron probably doesn't use dri3 anyway. But if you really to know more about this issue you probably should ask on stackoverflow where more specialized people will be able to help you. ^^'

Sorry I couldn't help you more.

**Comment by dMAC95** [comment]
doing  "github-desktop --no-sandbox" worked for me

**Comment by shiftkey** [comment]
Closing this out as we have an escape hatch for GPU-related issues that works independent of the command line - setting [`GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1`](https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-get-a-white-screen-when-launching-desktop) as an environment variable for the user.
