### ISSUE TITLE
meld support as mergetool under linux

### ISSUE THREAD

**Issue by jagiella** [shiftkey/desktop#896]
### The feature request

At the moment onlya GNOME Text Editor is available as merge tool despite having meld installed on my linux machine (debian / ubuntu).

![image](https://github.com/shiftkey/desktop/assets/4679834/3c43c998-3168-45f6-a699-4d3ea7f3411b)

I saw that a script for running meld is also installed on the system:
`/usr/lib/github-desktop/resources/app/git/libexec/git-core/mergetools/meld`

### Proposed solution

Would it be possible to integrate detection of a meld installation and use of meld as the default merge tool?

**Comment by shiftkey** [comment]
These integration settings are more to support external editors to interact with the repository files (e.g. open and interact with your files outside of Desktop), rather than tools which are part of the `git` workflow.

I'm not familiar enough with how `meld` would integrate into Desktop today, but based on https://stackoverflow.com/a/34119867/1363815 it seems like this is configured through `git difftool` and `git mergetool` and has a specific interface.

I'd suggest trying to set this through your `~/.gitconfig` and see how Desktop behaves, as I'm not up with the latest changes in this area...
