### ISSUE TITLE
Repositories are all gone

### ISSUE THREAD

**Issue by PadowYT2** [shiftkey/desktop#927]
### Operating System/Distribution

Zorin OS 16.3

### Installer

I was using 3.3.1, I was downgrading to a lot of version, to 3.2.9, then 3.2.7, then finally 3.2.0. Now I'm using 3.3.1 with my changes - [PadowYT2/desktop
](https://github.com/PadowYT2/desktop/releases/tag/release-3.3.1-16287)
### What happened?

By the time I was at 3.2.0, suddenly all my repositories are gone, except they are still present in the folder all with the `.git` folder

**Comment by PadowYT2** [comment]
I have solved this by drag-dropping the repo folders into the field, but why did this happen in the first place?

**Comment by mon-jai** [comment]
The list of repositories is stored in Electron/Chromium's IndexedDB using Dexie.

https://github.com/shiftkey/desktop/blob/d3be10b762932d0fea3866aa8fc1fb86c7a06a0d/app/src/lib/stores/repositories-store.ts#L170-L187

https://github.com/shiftkey/desktop/blob/d3be10b762932d0fea3866aa8fc1fb86c7a06a0d/app/src/lib/stores/repositories-store.ts#L57

https://github.com/shiftkey/desktop/blob/d3be10b762932d0fea3866aa8fc1fb86c7a06a0d/app/src/lib/databases/repositories-database.ts#L77

https://github.com/shiftkey/desktop/blob/d3be10b762932d0fea3866aa8fc1fb86c7a06a0d/app/src/lib/databases/base-database.ts#L1-L3

When you downgrade the app, the IndexedDB database probably gets reset because Chromium failed to read database files written by a newer version of itself.

**Comment by PadowYT2** [comment]
Thought it was an issue with GitHub dekstop, alright thank you!

**Comment by shiftkey** [comment]
> When you downgrade the app, the IndexedDB database probably gets reset because Chromium failed to read database files written by a newer version of itself.

This is correct. Downgrading by major versions of Chromium often means these databases used within the app are no longer compatible with the version of Chromium used, so they'll be reset. The Git repositories themselves are unaffected.
