### ISSUE TITLE
Can't open with nautilus

### ISSUE THREAD

**Issue by moritztim** [shiftkey/desktop#931]
### The problem

neither Help > "Show logs in your File Manager" nor \<repo\> > "Show in File Manager" do anything.

### Release version

Version 3.3.1-linux1 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. Open a repo
2. Click `Show in your File Manager`
or
1. Click `Help`
4. Click `Show logs in File Manager`
or
1. Click the current repo in the top left
2. right click one of the repos
5. Click `Show logs in FIle Manager`

### Log files

¯\\_(ツ)_/¯

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by moritztim** [comment]
I have found no relevant logs, only ones from august. Maybe I need to configure something for it to know about nautilus?
It could also be something completely different, since I've had some other issues with nautilus, such as drag and drop into another program not working and being unable to open it from some other application, I don't remember which tho.

**Comment by shiftkey** [comment]
> Maybe I need to configure something for it to know about nautilus?
It could also be something completely different, since I've had some other issues with nautilus, such as drag and drop into another program not working and being unable to open it from some other application, I don't remember which tho.

We're using Electron APIs to interact with the OS, in particular [`shell.openPath`](https://www.electronjs.org/docs/latest/api/shell#shellopenpathpath) which is just a [wrapper over `xdg-open` with a path being provided](https://github.com/electron/electron/blob/58a21a3cd939dcbb7d4282575a4e943bf30165ad/shell/common/platform_util_linux.cc#L300-L306) - if that's not working when you invoke it for a directory then perhaps that's a more definitive sign that something is busted with the Nautilus integration. 

Aside from that I'm not sure what else to try here, based on what's been provided so far.
