### ISSUE TITLE
Cannot Clone Private Repos with Github Desktop (forked from an org)

### ISSUE THREAD

**Issue by ForkedInTime** [shiftkey/desktop#973]
### The problem

I am using Github Desktop for the first time to clone a private repository that I forked from a bootcamp. I am able to clone the repository ok via CLI using 'gh clone thisrepository' bit, but I want to use Github Desktop. I am not able to clone the private repository as a window always pops with "Authentication Failed/Username/password required."

At the bottom of this pop up window it states: "Depending on your repository's hosting service, you might need to use a Personal Access Token (PAT) as your password. Learn more ... "

I created a basic PAT in Github but I do not think it is necessary because the repository is IN github. In any event, I tried different combinations to clone this private repository:

1) Username/pass to login to Github.com = ForkedInTime/pass
2) Username + PAT = ForkedInTime/Token
3) Username email + PAT = myprimaryemail/Token
4) Regenerated a new SSH key just in case and added it to the agent.

I am using Ubuntu 22.04. In summary, I cannot seem to clone these private repos that are FORKED from an organization to my github account - However,  I can clone them ok via CLI. Please advise.

### Release version

Version 3.3.5-linux2 (x64)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

1. Clone a private repo that is a fork of an organization's private repo
2. Select the URL tab
3. Clone
4. Authentication appears constantly  and will not accept any credentials (username/pass/token/PAT  etc)

### Log files

[2023-12-05.desktop..log](https://github.com/shiftkey/desktop/files/13554700/2023-12-05.desktop.log)

### Screenshots

![GithubDesktopAuth](https://github.com/shiftkey/desktop/assets/22755327/cb74ba22-0377-4723-a62a-7b460db52670)
![ForkedPrivateRepo](https://github.com/shiftkey/desktop/assets/22755327/c29dca48-11e6-4ac9-8681-594190d2ddf6)

### Additional context

To solve this issue I had to duplicate it with a different name. Downside:  I will never be able to update the forked repo because it's not synced to the real organization private repo. Three things happened:

1) The private repo name changed
2) The private repository is only mine and not a fork of the organization who created it (I no longer see a little lock up top when you hover your mouse over the original repo).
3) I can clone this private duplicate repo ok with Linux Github desktop & CLI

Looking at the logs it tells me that this private repo does not exist (it does). This is the cause but there is not enough verbosity to determine why Github desktop is confident that the repo does not exist.

**Comment by shiftkey** [comment]
@ForkedInTime looking at the logs it seems like the first attempt to clone it failed (because the app saw a 500 it seems to have failed given up and tried basic authentication):

```
2023-12-05T03:23:10.583Z - warn: [ui] deserialize: invalid JSON found at 'https://api.github.com/repos/ForkedInTime/ml-week-challenges' - status: 500, length: '0' id: 'C89C:68A2:EDEADB:1EBEC75:656E9790'
SyntaxError: Unexpected end of JSON input
2023-12-05T03:23:11.211Z - error: [ui] Failed to look up repository clone info for 'https://github.com/ForkedInTime/ml-week-challenges.git'
Error: API error https://api.github.com/repos/ForkedInTime/ml-week-challenges:  (500)
    at un (/home/yetipaw/webpack:/app/src/lib/http.ts:175:13)
    at Qn.fetchRepositoryCloneInfo (/home/yetipaw/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/yetipaw/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
```

It seems like the app was fine to take the custom credentials of some sort from that dialog:

```
2023-12-05T03:23:43.058Z - info: [ui] storing generic credentials for 'github.com' and 'hugeyeti@protonmail.com'
```

My best guess here is that those credentials didn't work for cloning the repository (we try and match by the hostname in the URL, but perhaps it's choosing a different set of credentials):

```
2023-12-05T03:23:43.513Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/ForkedInTime/ml-week-challenges.git /home/yetipaw/Documents/GitHub/ml-week-challenges` exited with an unexpected code: 128.
stderr:
Cloning into '/home/yetipaw/Documents/GitHub/ml-week-challenges'...
remote: Repository not found.
fatal: repository 'https://github.com/ForkedInTime/ml-week-challenges.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```

User repositories shouldn't be blocked from cloning, but there's details here that are missing:

> I created a basic PAT in Github but I do not think it is necessary because the repository is IN github.

The PAT permissions here could be why you were stuck (private repositories need a specific scope, and it's not clear to me what scopes you set).

Here's what I'd try in your situation:

 - remove any credentials from your OS credential store related to the app
 - do a fresh sign-in on the app
 - fork the repository to your user account again
 - from the app, open the "Clone a repository" dialog and see if your private fork appears

I can only see the `https://github.com/ForkedInTime/ml-week-challenges.git` repository in the logs so I can't speculate on the other options here...

**Comment by AZProductions** [comment]
I'm running into the same problem, forking a private repo causes the same error.
